# Generated by Django 6.0 on 2026-01-05 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payoutrequest',
            name='amount',
            field=models.DecimalField(choices=[(1000.0, '₦1,000.00'), (2000.0, '₦2,000.00'), (5000.0, '₦5,000.00'), (10000.0, '₦10,000.00')], decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='payoutrequest',
            name='status',
            field=models.CharField(default='PENDING', max_length=10),
        ),
    ]
