# Generated by Django 5.2.3 on 2026-01-03 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='tokens',
            field=models.IntegerField(default=0),
        ),
    ]
