# Generated by Django 6.0 on 2026-01-05 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_payoutrequest_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payoutrequest',
            name='account_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payoutrequest',
            name='account_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='payoutrequest',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
