# Generated by Django 6.0 on 2026-01-05 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_payoutrequest_account_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payoutrequest',
            name='account_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='payoutrequest',
            name='bank_name',
            field=models.CharField(blank=True, choices=[('', 'Select Bank'), ('access', 'Access Bank'), ('access_diamond', 'Access Bank (Diamond)'), ('ecobank', 'Ecobank Nigeria'), ('fidelity', 'Fidelity Bank'), ('firstbank', 'First Bank of Nigeria'), ('fcmb', 'First City Monument Bank (FCMB)'), ('gtbank', 'Guaranty Trust Bank (GTBank)'), ('heritage', 'Heritage Bank'), ('keystone', 'Keystone Bank'), ('kuda', 'Kuda Bank'), ('moniepoint', 'Moniepoint MFB'), ('opay', 'Opay'), ('palmpay', 'Palmpay'), ('polaris', 'Polaris Bank'), ('providus', 'Providus Bank'), ('stanbic', 'Stanbic IBTC Bank'), ('standard_chartered', 'Standard Chartered Bank'), ('sterling', 'Sterling Bank'), ('suntrust', 'Suntrust Bank'), ('union', 'Union Bank of Nigeria'), ('uba', 'United Bank for Africa (UBA)'), ('unity', 'Unity Bank'), ('wema', 'Wema Bank'), ('zenith', 'Zenith Bank')], max_length=100, null=True),
        ),
    ]
