# Generated by Django 6.0 on 2026-01-05 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_payoutrequest_account_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='discount_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='payoutrequest',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='payoutrequest',
            name='bank_name',
            field=models.CharField(blank=True, choices=[('', 'Select Bank'), ('access', 'Access Bank'), ('ecobank', 'Ecobank Nigeria'), ('fidelity', 'Fidelity Bank'), ('firstbank', 'First Bank of Nigeria'), ('gtbank', 'Guaranty Trust Bank (GTBank)'), ('kuda', 'Kuda Bank'), ('opay', 'Opay'), ('palmpay', 'Palmpay'), ('uba', 'United Bank for Africa (UBA)'), ('zenith', 'Zenith Bank')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='profile',
            name='earnings',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
