# Generated by Django 6.0 on 2026-01-05 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_item_discount_price_alter_item_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='earnings',
            new_name='token_rewards',
        ),
    ]
