# Generated by Django 5.2.3 on 2026-01-03 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_payoutrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payoutrequest',
            name='payment_details',
        ),
        migrations.AddField(
            model_name='payoutrequest',
            name='account_name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payoutrequest',
            name='account_number',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payoutrequest',
            name='bank_name',
            field=models.CharField(choices=[('Access Bank', 'Access Bank'), ('GTBank', 'Guaranty Trust Bank'), ('First Bank', 'First Bank of Nigeria'), ('UBA', 'United Bank for Africa'), ('Zenith Bank', 'Zenith Bank'), ('Kuda', 'Kuda Microfinance Bank'), ('OPay', 'OPay'), ('PalmPay', 'PalmPay'), ('Other', 'Other')], default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='saved_account_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='saved_account_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='saved_bank_name',
            field=models.CharField(blank=True, choices=[('Access Bank', 'Access Bank'), ('GTBank', 'Guaranty Trust Bank'), ('First Bank', 'First Bank of Nigeria'), ('UBA', 'United Bank for Africa'), ('Zenith Bank', 'Zenith Bank'), ('Kuda', 'Kuda Microfinance Bank'), ('OPay', 'OPay'), ('PalmPay', 'PalmPay'), ('Other', 'Other')], max_length=100, null=True),
        ),
    ]
