# Generated by Django 5.2.3 on 2026-01-03 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_payoutrequest_payment_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payoutrequest',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Admin: If rejecting, explain why here.', null=True),
        ),
    ]
