# Generated by Django 6.0 on 2026-01-05 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_earnings_profile_token_rewards'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payoutrequest',
            name='bank_name',
            field=models.CharField(blank=True, choices=[('', 'Select Bank'), ('access', 'Access Bank'), ('ecobank', 'Ecobank Nigeria'), ('fidelity', 'Fidelity Bank'), ('firstbank', 'First Bank of Nigeria'), ('gtbank', 'Guaranty Trust Bank (GTBank)'), ('kuda', 'Kuda Bank'), ('moniepoint', 'Moniepoint MFB'), ('opay', 'Opay'), ('palmpay', 'Palmpay'), ('uba', 'United Bank for Africa (UBA)'), ('zenith', 'Zenith Bank')], max_length=100, null=True),
        ),
    ]
