# Generated by Django 5.2.3 on 2026-01-03 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_payoutrequest_rejection_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='discount_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Optional: Show a strike-through price', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='payoutrequest',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
