# Generated by Django 6.0.1 on 2026-02-02 12:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_chatmessage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductReferral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clicks', models.PositiveIntegerField(default=0)),
                ('last_click', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_clicks', to='core.item')),
                ('referrer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_referrals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('referrer', 'item')},
            },
        ),
    ]
