# Generated by Django 5.2.3 on 2026-01-03 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_item_discount_price_item_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='is_featured',
            field=models.BooleanField(default=False, help_text="Check this to show as 'Review of the Week'"),
        ),
    ]
