# Generated by Django 6.0.1 on 2026-02-02 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_item_expiry_date_alter_payoutrequest_bank_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotionplan',
            name='affiliate_link',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='promotionplan',
            name='duration_days',
            field=models.IntegerField(choices=[(7, 'Weekly - ₦5,000'), (30, 'Monthly - ₦10,000'), (180, '6 Months - ₦50,000'), (365, '1 Year - ₦100,000')]),
        ),
    ]
