# Generated by Django 6.0.1 on 2026-02-02 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_promotionplan_affiliate_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotionplan',
            name='affiliate_link',
        ),
    ]
