# Generated by Django 6.0.1 on 2026-02-02 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_promotionplan_affiliate_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotionplan',
            name='subscription_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
