# Generated by Django 6.0.1 on 2026-02-03 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_promotionplan_subscription_expiry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotionplan',
            name='commission_per_click',
        ),
        migrations.AddField(
            model_name='item',
            name='commission_naira',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='promotionplan',
            name='commission_percentage',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='promotionplan',
            name='product_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
