# Generated by Django 6.0.1 on 2026-02-03 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_promotionplan_commission_per_click_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_type',
            field=models.CharField(choices=[('MARKETER', 'Marketer (Promote & Earn)'), ('ADVERTISER', 'Advertiser (List Products)')], default='MARKETER', max_length=20),
        ),
    ]
