# Generated by Django 6.0.1 on 2026-02-04 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_profile_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='account_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='account_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='bank_name',
            field=models.CharField(blank=True, choices=[('', 'Select Bank'), ('access', 'Access Bank'), ('gtbank', 'GTBank'), ('kuda', 'Kuda'), ('opay', 'Opay'), ('palmpay', 'Palmpay'), ('zenith', 'Zenith')], max_length=100, null=True),
        ),
    ]
