# Generated by Django 6.0.1 on 2026-02-04 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_item_whatsapp_number_promotionplan_whatsapp_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotionplan',
            name='whatsapp_number',
        ),
        migrations.AddField(
            model_name='profile',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='promotionplan',
            name='destination_type',
            field=models.CharField(choices=[('whatsapp', 'WhatsApp'), ('website', 'Website')], default='whatsapp', max_length=10),
        ),
        migrations.AddField(
            model_name='promotionplan',
            name='website_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='website',
            field=models.URLField(blank=True, help_text='Direct link for website owners', null=True),
        ),
    ]
