# Generated by Django 6.0.1 on 2026-02-05 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_remove_promotionplan_whatsapp_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='affiliate_link',
        ),
        migrations.AddField(
            model_name='promotionplan',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='payoutrequest',
            name='bank_name',
            field=models.CharField(blank=True, choices=[('', 'Select Bank'), ('access', 'Access Bank'), ('ecobank', 'Ecobank'), ('fidelity', 'Fidelity Bank'), ('firstbank', 'First Bank of Nigeria'), ('fcmb', 'First City Monument Bank (FCMB)'), ('gtbank', 'Guaranty Trust Bank (GTBank)'), ('heritage', 'Heritage Bank'), ('keystone', 'Keystone Bank'), ('kuda', 'Kuda Microfinance Bank'), ('moniepoint', 'Moniepoint MFB'), ('opay', 'Opay'), ('palmpay', 'Palmpay'), ('polaris', 'Polaris Bank'), ('stanbic', 'Stanbic IBTC Bank'), ('sterling', 'Sterling Bank'), ('union', 'Union Bank'), ('uba', 'United Bank for Africa (UBA)'), ('unity', 'Unity Bank'), ('wema', 'Wema Bank'), ('zenith', 'Zenith Bank')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='payoutrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('FAILED', 'Failed')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bank_name',
            field=models.CharField(blank=True, choices=[('', 'Select Bank'), ('access', 'Access Bank'), ('ecobank', 'Ecobank'), ('fidelity', 'Fidelity Bank'), ('firstbank', 'First Bank of Nigeria'), ('fcmb', 'First City Monument Bank (FCMB)'), ('gtbank', 'Guaranty Trust Bank (GTBank)'), ('heritage', 'Heritage Bank'), ('keystone', 'Keystone Bank'), ('kuda', 'Kuda Microfinance Bank'), ('moniepoint', 'Moniepoint MFB'), ('opay', 'Opay'), ('palmpay', 'Palmpay'), ('polaris', 'Polaris Bank'), ('stanbic', 'Stanbic IBTC Bank'), ('sterling', 'Sterling Bank'), ('union', 'Union Bank'), ('uba', 'United Bank for Africa (UBA)'), ('unity', 'Unity Bank'), ('wema', 'Wema Bank'), ('zenith', 'Zenith Bank')], max_length=100, null=True),
        ),
    ]
