# Generated by Django 6.0.1 on 2026-02-06 07:59

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_remove_item_affiliate_link_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productreferral',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='item',
            name='discount_price',
        ),
        migrations.RemoveField(
            model_name='item',
            name='specifications',
        ),
        migrations.AddField(
            model_name='profile',
            name='verification_status',
            field=models.CharField(choices=[('UNVERIFIED', 'Unverified'), ('PENDING', 'Pending Review'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], default='UNVERIFIED', max_length=20),
        ),
        migrations.AlterField(
            model_name='item',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='payoutrequest',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='payoutrequest',
            name='status',
            field=models.CharField(default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bank_name',
            field=models.CharField(blank=True, choices=[('', 'Select Bank'), ('gtbank', 'GTBank'), ('zenith', 'Zenith Bank'), ('opay', 'Opay'), ('kuda', 'Kuda')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.CharField(choices=[('MARKETER', 'Marketer'), ('ADVERTISER', 'Advertiser')], default='MARKETER', max_length=20),
        ),
        migrations.AlterField(
            model_name='promotionplan',
            name='duration_days',
            field=models.IntegerField(choices=[(7, 'Weekly'), (30, 'Monthly'), (180, '6 Months'), (365, '1 Year')]),
        ),
        migrations.CreateModel(
            name='AdvertiserVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=255)),
                ('full_name', models.CharField(max_length=255)),
                ('contact_number', models.CharField(max_length=20)),
                ('residential_address', models.TextField()),
                ('proof_of_identity', models.FileField(upload_to=core.models.secure_verification_path)),
                ('proof_of_address', models.FileField(upload_to=core.models.secure_verification_path)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verification_docs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
