# Generated by Django 6.0.1 on 2026-02-06 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_productreferral_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(help_text='e.g., Weekly Plan', max_length=50)),
                ('duration_days', models.IntegerField(help_text='Must match 7, 30, 180, or 365', unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
            options={
                'verbose_name': 'Plan Price Setting',
                'verbose_name_plural': 'Plan Price Settings',
            },
        ),
    ]
