# Generated by Django 6.0.1 on 2026-02-06 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_subscriptionprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotionplan',
            name='agree_to_commissions',
            field=models.BooleanField(default=False),
        ),
    ]
