# Generated by Django 6.0.1 on 2026-02-06 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_promotionplan_agree_to_commissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotionplan',
            name='duration_days',
            field=models.IntegerField(),
        ),
    ]
