# Generated by Django 6.0.1 on 2026-02-06 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_promotionplan_duration_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotionplan',
            name='commission_percentage',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
