# Generated by Django 6.0.1 on 2026-02-19 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_alter_promotionplan_commission_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bank_name',
            field=models.CharField(blank=True, choices=[('', 'Select Bank'), ('access', 'Access Bank'), ('citibank', 'Citibank Nigeria'), ('ecobank', 'Ecobank Nigeria'), ('fidelity', 'Fidelity Bank'), ('firstbank', 'First Bank of Nigeria'), ('fcmb', 'First City Monument Bank (FCMB)'), ('globus', 'Globus Bank'), ('gtbank', 'Guaranty Trust Bank (GTB)'), ('keystone', 'Keystone Bank'), ('optimus', 'Optimus Bank'), ('polaris', 'Polaris Bank'), ('premium', 'Premium Trust Bank'), ('providus', 'Providus Bank'), ('stanbic', 'Stanbic IBTC Bank'), ('standard', 'Standard Chartered Bank'), ('sterling', 'Sterling Bank'), ('suntrust', 'SunTrust Bank'), ('titan', 'Titan Trust Bank'), ('union', 'Union Bank of Nigeria'), ('uba', 'United Bank for Africa (UBA)'), ('unity', 'Unity Bank'), ('wema', 'Wema Bank'), ('zenith', 'Zenith Bank'), ('opay', 'OPay (Digital)'), ('palmpay', 'PalmPay'), ('kuda', 'Kuda Bank'), ('moniepoint', 'Moniepoint MFB'), ('fairmoney', 'FairMoney MFB'), ('vfd', 'VBank (VFD)'), ('carbon', 'Carbon')], max_length=100, null=True),
        ),
    ]
