# Generated by Django 6.0.1 on 2026-02-19 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriptionprice',
            options={},
        ),
        migrations.RemoveField(
            model_name='item',
            name='website',
        ),
        migrations.AddField(
            model_name='item',
            name='external_url',
            field=models.URLField(blank=True, help_text='Direct link for Agency items (e.g. Travelstart)', null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='is_escrow_required',
            field=models.BooleanField(default=True, help_text="Uncheck for Admin/Agency items that don't need internal payment."),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bank_name',
            field=models.CharField(blank=True, choices=[('', 'Select Bank'), ('access', 'Access Bank'), ('gtbank', 'GTB'), ('zenith', 'Zenith Bank'), ('opay', 'OPay'), ('kuda', 'Kuda Bank'), ('palmpay', 'PalmPay'), ('moniepoint', 'Moniepoint MFB')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='subscriptionprice',
            name='duration_days',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='subscriptionprice',
            name='plan_name',
            field=models.CharField(max_length=50),
        ),
    ]
