# Generated by Django 6.0.2 on 2026-02-23 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_alter_subscriptionprice_options_remove_item_website_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_delivered',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='commission_earned',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
