# Generated by Django 6.0.2 on 2026-02-23 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_order_is_delivered_alter_order_commission_earned'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='refund_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Waiting for Payment'), ('PAID', 'Paid - Funds Held in Escrow'), ('SHIPPED', 'In Transit'), ('COMPLETED', 'Delivered & Funds Released'), ('REFUNDED', 'Refunded to Buyer'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.CharField(choices=[('MARKETER', 'Marketer'), ('ADVERTISER', 'Advertiser'), ('BUYER', 'Buyer')], default='MARKETER', max_length=20),
        ),
    ]
