# Generated by Django 6.0.2 on 2026-02-25 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_order_refund_deadline_alter_order_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bank_name',
            field=models.CharField(blank=True, choices=[('', 'Select Bank'), ('044', 'Access Bank'), ('050', 'Ecobank'), ('070', 'Fidelity Bank'), ('011', 'First Bank of Nigeria'), ('214', 'First City Monument Bank (FCMB)'), ('058', 'Guaranty Trust Bank (GTB)'), ('030', 'Heritage Bank'), ('082', 'Keystone Bank'), ('50211', 'Kuda Bank'), ('50515', 'Moniepoint MFB'), ('999992', 'OPay'), ('999991', 'PalmPay'), ('076', 'Polaris Bank'), ('221', 'Stanbic IBTC Bank'), ('068', 'Standard Chartered Bank'), ('232', 'Sterling Bank'), ('032', 'Union Bank of Nigeria'), ('033', 'United Bank for Africa (UBA)'), ('035', 'Wema Bank'), ('057', 'Zenith Bank')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Seller Contact Info'),
        ),
    ]
