# Generated by Django 6.0.2 on 2026-03-02 22:43

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_faq'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faq',
            options={'ordering': ['created_at']},
        ),
        migrations.RemoveField(
            model_name='advertiserverification',
            name='contact_number',
        ),
        migrations.RemoveField(
            model_name='advertiserverification',
            name='proof_of_address',
        ),
        migrations.AddField(
            model_name='advertiserverification',
            name='nin_number',
            field=models.CharField(default='00000000000', help_text='11-digit National Identification Number', max_length=11),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='advertiserverification',
            name='full_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='advertiserverification',
            name='proof_of_identity',
            field=models.FileField(help_text='Upload NIN slip or Card image', upload_to=core.models.secure_verification_path),
        ),
        migrations.AlterField(
            model_name='advertiserverification',
            name='residential_address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='faq',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
